apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}
spec:
  dnsNames:
    - {{ .Values.hostName }}
  duration: 2160h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h0m0s
  secretName: {{ .Values.certificate.secretName }}
  subject:
    organizations:
      - Scientist, Inc.
  usages:
    - server auth
    - client auth
